# Generated by Django 2.1.7 on 2019-03-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190316_1529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='BonusSettings',
        ),
    ]
