# Generated by Django 2.1.7 on 2019-03-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190316_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonustype',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
