# Generated by Django 2.1.7 on 2019-03-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_bonustype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonustype',
            name='code',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
