# Generated by Django 2.1.7 on 2019-03-18 15:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190317_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
