# Generated by Django 2.1.7 on 2019-05-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_node_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
