# Generated by Django 2.1.7 on 2019-06-03 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20190602_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='package',
        ),
        migrations.AddField(
            model_name='node',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Package'),
        ),
    ]
