# Generated by Django 2.1.7 on 2019-06-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190603_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
