# Generated by Django 2.1.7 on 2019-06-03 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_package_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='user',
        ),
        migrations.AddField(
            model_name='bonus',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_node', to='account.Node'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_partner', to='account.Node'),
        ),
    ]
