# Generated by Django 2.1.7 on 2019-06-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20190603_1746'),
        ('account', '0010_node_status'),
    ]

    operations = [
    ]
