# Generated by Django 2.1.7 on 2019-07-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_merge_20190605_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyValueSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
    ]
