# Generated by Django 2.1.7 on 2019-07-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_propertyvaluesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_processed',
            field=models.BooleanField(default=0),
        ),
    ]
