# Generated by Django 2.1.5 on 2019-04-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [

    ]
