# Generated by Django 2.1.5 on 2019-04-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190403_1820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='News',
        ),
    ]
